server:
  port: 8899

spring:
  application:
    name: diablo
  main:
    allow-bean-definition-overriding: true

diablo:

  web:
    keepAliveUpstream:
      scanTimeMillisecond: 1000
    disruptor:
      bufferSize: 2048
      threadSize: 1
    accessLog:
      enable: true
      percentagy: 100
    redis:
      nodes: 127.0.0.1:6379
    sync:
      strategy: http
      url: http://localhost:8887
    leakDetection:
      level: SIMPLE

logging:
  level:
    root: info
